" Enable syntax highlighting
syntax enable

" Set colorscheme
"colorscheme default


" Set backup dir so vim doesn't write backups where we don't want
set bdir=~/.vim/temp/backups

" Set swap dir so vim doesn't write swaps to current (possibly readonly) directory
set dir=~/.vim/temp/swaps

" Set font if gvim is loaded
" If ~/.gvimrc exists that would override this setting
set guifont=Fira\ Mono\ 12



set number		" Display line numbers
set tabstop=4		" Set tab length to 4

" For indenting 4 spaces is nice
set shiftwidth=4
set softtabstop=4


" Default encoding
"set encoding=utf-8


" Set line ending mode (dos or unix)
set fileformats=unix,dos
set ff=unix


" Ignore case (case insensitivity) in search using / etc.
set ignorecase


" Set vim window size and position on startup
" Practical config
"winsize 122 32
"winpos 110 40


" Don't show toolbar in gvim
"set guioptions-=T


" Tab names (tab title) format
set guitablabel=%t\ %m


" Automatically indent
set autoindent
set smartindent


" Automatically set current dir to where file is opened, or active buffer
set autochdir


" Define some useful macros
" Prepend starting C-style multiline comment to current line
"a=mwO/*`w

" Append Ending C-style multiline comment
"b=mwo*/`w

" Prepend C++ style single line comment to current line
"c=mw^i//`wll

" Remove C++ style comment from beginning of current line
"d=mwV:s/\/\//`whh:noh

let @a='my^i//.`yll'
let @b='my^2x`yhh'
let @c=':!php -l %;read'


" Set cursor shape and behavious in gvim
"set guicursor=n-v-ci:nCursor-hor30-blinkwait10-blinkon300-blinkoff100
"set guicursor+=i:iCursor-ver25-blinkwait10-blinkon150-blinkoff100


" Set useful keymaps
" Use <c-j> and <c-k> in normal mode to switch between buffers
nmap <c-j> <esc>:bp<cr>
nmap <c-k> <esc>:bn<cr>

nmap cfp :let @* = expand("%:p")<cr>


" Commands required by pathogen
"if exists('pathogen#infect')
"	filetype off
"	execute pathogen#infect()
"	execute pathogen#helptags()
"	filetype plugin indent on
"endif
"syntax on
call pathogen#infect()


" Make mks command save global variables/functions too
setg sessionoptions+=globals


" Setting the cursor appearance
"highlight iCursor guibg=red
"highlight nCursor guibg=green


" Fortran
"if has("fname_case")
"  au BufNewFile,BufRead *.FOR,*.FPP,*.FTN,*.F77,*.F90,*.F95,*.F03,*.F08	 setf fortran
"endif
"au BufNewFile,BufRead   *.for,*.fortran,*.fpp,*.ftn,*.f77,*.f90,*.f95,*.f03,*.f08  setf fortran

" Forth
au BufNewFile,BufRead *.FS,*.SEQ,*.seq,*.FT,*.F,*.FOR,*.4TH,*.FRT,*.fs,*.ft,*.f,*.for,*.4th,*.frt setf forth
